import bcrypt from 'bcryptjs';
const data = {
  categories:[
    {
      name:"Men",
    },
    {
      name:"Women",
    },
    {
      name:"Boys",
    },
    {
      name:"Pants",
    },
    {
      name:"Shirts",
    },
  ],
  users:[
    {
      name:'Admin-user',
      email:'admin@gmail.com',
      password: bcrypt.hashSync('1234',8),
      isAdmin:true,
      isSeller:true,

    },
    {
      name:'seller',
      email:'seller@gmail.com',
      password: bcrypt.hashSync('1234',8),
      isAdmin:false,
      isSeller:true,
    },
    {
      name:'user',
      email:'user@gmail.com',
      password: bcrypt.hashSync('1234',8),
      isAdmin:false,
      isSeller:false,
    },
    
    
  ],
    products: [
      {
        name: 'Tommy Hilfiger Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Lacoste Slim Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Hollister Slim Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt3.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: "Men's T-Shirt",
        category: 'Men Shirts',
        image: '/images/mshirt4.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Nike Slim',
        category: 'Men Shirts',
        image: '/images/mshirt5.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Nike Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt6.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Slim Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt7.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Overshirt',
        category: 'Men Shirts',
        image: '/images/mshirt8.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Classic Short Sleeve Shirt.',
        category: 'Men Shirts',
        image: '/images/mshirt9.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      
      {
        name: 'Mandarin Collar Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt11.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Polo Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt12.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Denim Shirt',
        category: 'Men Shirts',
        image: '/images/mshirt13.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Granddad shirt',
        category: 'Men Shirts',
        image: '/images/mshirt14.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Flannel shirt',
        category: 'Men Shirts',
        image: '/images/mshirt15.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Dress shirt',
        category: 'Men Shirts',
        image: '/images/mshirt16.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Girl Shirts',
        category: 'Men Shirts',
        image: '/images/mshirt17.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'T-Shirt',
        category: 'Women Shirts',
        image: '/images/gshirt29.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Women Shirt',
        category: 'Women Shirts',
        image: '/images/gshirt1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Bardot Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Bralette Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt4.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Blouson Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt5.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Camisole Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt6.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Sweaters Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt7.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Long Seleeves Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt8.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Fjord Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt9.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      
      {
        name: 'Tuxedo Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt11.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Peplum Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt12.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Gypsy Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt13.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Sailor Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt14.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Tunic Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt15.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Military Shirt',
        category: 'Women Shirts',
        image: '/images/gshirt16.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
    
      {
        name: 'Sweat Shirt',
        category: 'Women Shirts',
        image: '/images/gshirt18.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Henly Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt19.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
    
      {
        name: 'Ruffle Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt21.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'V-Neck Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt22.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Simple Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt23.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Slim Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt24.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Nike Simple Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt25.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
      {
        name: 'Ca Simple  Shirts',
        category: 'Women Shirts',
        image: '/images/gshirt26.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        seller:"60cf50416442151674b761b3"
      },
    
      
    ],
  };
  export default data;